title: 小横竖相关收集站
description: 以心相系华夏
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
lang: zh-cmn-Hans
github:
  is_project_page: false